# Use Node.js as the base image
FROM node:20-slim AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . ./

# Build the application
RUN npm run build

# Use a smaller web server to serve the static files
FROM nginx:alpine

# Copy the build files to the nginx server
COPY --from=build /app/dist /usr/share/nginx/html

# Copy our custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf


# Expose the port on which nginx will serve
EXPOSE 80

# Run nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
